# Basic Image Processing with OpenCV using Python

## Topic 1: Reading Images,Videos & Webcams

### 1.1 : Reading Image

In [6]:
import cv2
print("Package Imported")
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
cv2.imshow("Output",img)
cv2.waitKey(0)

Package Imported


-1

### 1.2 : Reading Video

In [ ]:
import cv2
frameWidth = 640
frameHeight = 480
cap = cv2.VideoCapture("Desktop/python/OPENCV Basics/video.mp4")
while True:
    success, img = cap.read()
    img = cv2.resize(img, (frameWidth, frameHeight))
    cv2.imshow("Result", img)
    if cv2.waitKey(1) and 0xFF == ord('q'):
         break

### 1.3 : Reading Webcam

In [ ]:
import cv2
frameWidth = 640
frameHeight = 480
cap = cv2.VideoCapture(0)
cap.set(3, frameWidth)
cap.set(4, frameHeight)
cap.set(10,150)
while True:
    success, img = cap.read()
    cv2.imshow("Result", img)
    if cv2.waitKey(1) and 0xFF == ord('q'):
        break


## Topic 2: Basic OpenCV Functions

### 2.1 : Grayscaling Image

In [2]:
import cv2
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
Grayimg = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("Original Image",img)
cv2.imshow("Gray Image",Grayimg)
cv2.waitKey(0)

-1

### 2.2 : Blurring Image

In [4]:
import cv2
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
Blurimg = cv2.GaussianBlur(img,(7,7),0)
cv2.imshow("Original Image",img)
cv2.imshow("Blurred Image",Blurimg)
cv2.waitKey(0)

-1

### 2.3 : Edge Detector(Canny Image)

In [6]:
import cv2
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
Cannyimg = cv2.Canny(img,150,200)
cv2.imshow("Original Image",img)
cv2.imshow("Canny Image",Cannyimg)
cv2.waitKey(0)

-1

###  2.4 : Dialating Image

In [10]:
import cv2
import numpy as np
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
kernel = np.ones((5,5),np.uint8)
Dialationimg = cv2.dilate(Cannyimg,kernel,iterations=1)
cv2.imshow("Original Image",img)
cv2.imshow("Dialated Image",Dialationimg)
cv2.waitKey(0)

-1

### 2.5 : Eroding Image

In [11]:
import cv2
import numpy as np
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
kernel = np.ones((5,5),np.uint8)
Erodedimg = cv2.erode(Dialationimg,kernel,iterations=1)
cv2.imshow("Original Image",img)
cv2.imshow("Eroded Image",Erodedimg)
cv2.waitKey(0)

-1

## Topic 3: Resizing & Cropping an Image

In [13]:
import cv2
import numpy as np
 
img = cv2.imread("Desktop/python/OPENCV Basics/cena.jpg")
print(img.shape)
 
imgResize = cv2.resize(img,(1000,500))## First Co-ordinate is Width, Second Co-ordinate is Height
print(imgResize.shape)
 
imgCropped = img[0:200,200:500]## First Co-ordinate is Height,Second Co-ordinate Width
 
cv2.imshow("Image",img)
cv2.imshow("Image Resize",imgResize)
cv2.imshow("Image Cropped",imgCropped)
 
cv2.waitKey(0)


(1777, 2370, 3)
(500, 1000, 3)


-1

## Topic 4 : Shapes & Text

### 4.1 : Creating a Colored Image

In [18]:
import cv2
import numpy as np

img = np.zeros((512,512,3),np.uint8)
print(img)
img[:] = 255,0,0
cv2.imshow("Image",img)
cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


-1

## Topic 5: Warp Perspective

In [19]:
import cv2
import numpy as np
 
img = cv2.imread("Desktop/python/OPENCV Basics/card.jpg")
 
width,height = 250,350
pts1 = np.float32([[111,219],[287,188],[154,482],[352,440]])
pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix = cv2.getPerspectiveTransform(pts1,pts2)
imgOutput = cv2.warpPerspective(img,matrix,(width,height))
 
cv2.imshow("Image",img)
cv2.imshow("Output",imgOutput)
cv2.waitKey(0)

-1

## Topic 6: Stacking Images

In [20]:
import cv2
import numpy as np
 
 
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

img = cv2.imread("Desktop/python/OPENCV Basics/card.jpg")
 
width,height = 250,350
pts1 = np.float32([[111,219],[287,188],[154,482],[352,440]])
pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix = cv2.getPerspectiveTransform(pts1,pts2)
imgOutput = cv2.warpPerspective(img,matrix,(width,height))

imgGray = cv2.cvtColor(imgOutput,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),0)
imgCanny = cv2.Canny(imgOutput,150,200)
imgDialation = cv2.dilate(imgCanny,kernel,iterations=1)
imgEroded = cv2.erode(imgDialation,kernel,iterations=1)
 
imgStack = stackImages(0.5,([imgOutput,imgGray,imgBlur],[imgCanny,imgDialation,imgEroded]))

cv2.imshow("ImageStack",imgStack)
 
cv2.waitKey(0)

-1

## Topic 7: Color Detection

### Detecting Color of an Image

In [ ]:
import cv2
import numpy as np
 
def empty(a):
    pass
 
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver
 
 
path = 'Desktop/python/OPENCV Basics/lambo.png'
cv2.namedWindow("TrackBars")
cv2.resizeWindow("TrackBars",640,240)
cv2.createTrackbar("Hue Min","TrackBars",0,179,empty)
cv2.createTrackbar("Hue Max","TrackBars",19,179,empty)
cv2.createTrackbar("Sat Min","TrackBars",110,255,empty)
cv2.createTrackbar("Sat Max","TrackBars",240,255,empty)
cv2.createTrackbar("Val Min","TrackBars",153,255,empty)
cv2.createTrackbar("Val Max","TrackBars",255,255,empty)
 
while True:
    img = cv2.imread(path)
    imgHSV = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    h_min = cv2.getTrackbarPos("Hue Min","TrackBars")
    h_max = cv2.getTrackbarPos("Hue Max", "TrackBars")
    s_min = cv2.getTrackbarPos("Sat Min", "TrackBars")
    s_max = cv2.getTrackbarPos("Sat Max", "TrackBars")
    v_min = cv2.getTrackbarPos("Val Min", "TrackBars")
    v_max = cv2.getTrackbarPos("Val Max", "TrackBars")
    print(h_min,h_max,s_min,s_max,v_min,v_max)
    lower = np.array([h_min,s_min,v_min])
    upper = np.array([h_max,s_max,v_max])
    mask = cv2.inRange(imgHSV,lower,upper)
    imgResult = cv2.bitwise_and(img,img,mask=mask)
 
 
    # cv2.imshow("Original",img)
    # cv2.imshow("HSV",imgHSV)
    # cv2.imshow("Mask", mask)
    # cv2.imshow("Result", imgResult)
 
    imgStack = stackImages(0.6,([img,imgHSV],[mask,imgResult]))
    cv2.imshow("Stacked Images", imgStack)
    cv2.waitKey(0)

0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 153 255
0 19 110 240 

### Color Detection Using Webcam

In [ ]:
import cv2
import numpy as np
  
frameWidth = 640
frameHeight = 480
cap = cv2.VideoCapture(0)
cap.set(3, frameWidth)
cap.set(4, frameHeight)
frameCounter = 0
  
def empty(a):
    pass
  
cv2.namedWindow("HSV")
cv2.resizeWindow("HSV", 640, 240)
cv2.createTrackbar("HUE Min", "HSV", 0, 179, empty)
cv2.createTrackbar("HUE Max", "HSV", 179, 179, empty)
cv2.createTrackbar("SAT Min", "HSV", 0, 255, empty)
cv2.createTrackbar("SAT Max", "HSV", 255, 255, empty)
cv2.createTrackbar("VALUE Min", "HSV", 0, 255, empty)
cv2.createTrackbar("VALUE Max", "HSV", 255, 255, empty)
  
  
while True:
    frameCounter +=1
    if cap.get(cv2.CAP_PROP_FRAME_COUNT) ==frameCounter:
        cap.set(cv2.CAP_PROP_POS_FRAMES,0)
        frameCounter=0
  
    _, img = cap.read()
    imgHsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
  
    h_min = cv2.getTrackbarPos("HUE Min", "HSV")
    h_max = cv2.getTrackbarPos("HUE Max", "HSV")
    s_min = cv2.getTrackbarPos("SAT Min", "HSV")
    s_max = cv2.getTrackbarPos("SAT Max", "HSV")
    v_min = cv2.getTrackbarPos("VALUE Min", "HSV")
    v_max = cv2.getTrackbarPos("VALUE Max", "HSV")
    print(h_min)
  
    lower = np.array([h_min, s_min, v_min])
    upper = np.array([h_max, s_max, v_max])
    mask = cv2.inRange(imgHsv, lower, upper)
    result = cv2.bitwise_and(img, img, mask=mask)
  
    mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
    hStack = np.hstack([img, mask, result])
    cv2.imshow('Horizontal Stacking', hStack)
    if cv2.waitKey(1) and 0xFF == ord('q'):
        break
  
cap.release()
cv2.destroyAllWindows()


## Topic 8 : Contours & Shape

In [1]:
import cv2
import numpy as np
 
def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver
 
def getContours(img):
    contours,hierarchy = cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
    for cnt in contours:
        area = cv2.contourArea(cnt)
        print(area)
        if area>500:
            cv2.drawContours(imgContour, cnt, -1, (255, 0, 0), 3)
            peri = cv2.arcLength(cnt,True)
            #print(peri)
            approx = cv2.approxPolyDP(cnt,0.02*peri,True)
            print(len(approx))
            objCor = len(approx)
            x, y, w, h = cv2.boundingRect(approx)
 
            if objCor ==3: objectType ="Tri"
            elif objCor == 4:
                aspRatio = w/float(h)
                if aspRatio >0.98 and aspRatio <1.03: objectType= "Square"
                else:objectType="Rectangle"
            elif objCor>4: objectType= "Circles"
            else:objectType="None"
 
 
 
            cv2.rectangle(imgContour,(x,y),(x+w,y+h),(0,255,0),2)
            cv2.putText(imgContour,objectType,
                        (x+(w//2)-10,y+(h//2)-10),cv2.FONT_HERSHEY_COMPLEX,0.7,
                        (0,0,0),2)
 
 
path = 'Desktop/python/OPENCV Basics/shapes.png'
img = cv2.imread(path)
imgContour = img.copy()
 
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),1)
imgCanny = cv2.Canny(imgBlur,50,50)
getContours(imgCanny)
 
imgBlank = np.zeros_like(img)
imgStack = stackImages(0.8,([img,imgGray,imgBlur],
                            [imgCanny,imgContour,imgBlank]))
 
cv2.imshow("Stack", imgStack)
cv2.waitKey(0)


3593.5
8
8619.0
4
10398.5
4
10236.0
8
1612.5
3
10402.0
4
6389.0
4
5629.0
3
3475.5
4
2270.5
4
3552.5
8
8674.0
4
2646.0
4
5690.5
3
10234.0
8
5712.0
3


-1

## Topic 8: Face Detection

### Haarcascade is used to detect many parts in any object 

In [2]:
import cv2
 
faceCascade= cv2.CascadeClassifier("Desktop/python/OPENCV Basics/haarcascades/haarcascade_frontalface_default.xml")
img = cv2.imread('Desktop/python/OPENCV Basics/cena.jpg')
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
 
faces = faceCascade.detectMultiScale(imgGray,1.1,4)
 
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
 
cv2.imshow("Result", img)
cv2.waitKey(0)

-1